### ISSUE TITLE
Version 1.1.0 breaks image uploads in WordPress 4.3.x and up

### ISSUE THREAD

**Issue by pauljacobson** [indieweb/wordpress-indieauth#1]
I have version 1.1.0 installed on my WordPress 4.4.1 blog and I noticed that images weren't uploading through the iOS, Mac desktop apps or through the Web through mobile iOS. I worked through a number of IndieWeb plugins and this specific one seems to be responsible for breaking the uploads.

I have tested my site with WordPress support and checked folder permissions. This seems to be the cause of the issue. I noticed that the plugin has been updated to version 1.1.1 but this hasn't rolled out to WordPress updates yet so I haven't tested my uploads with version 1.1.1.

**Comment by idallas** [comment]
I'm seeing this issue as well, with version 1.1.2.  I think it's specifically when using Jetpack and connecting the site to wordpress.com.

**Comment by dshanske** [comment]
@idallas Version 2.0 completely rewrote the plugin. Can you check again so we can close this?

**Comment by idallas** [comment]
@dshanske It's been awhile and I've forgotten exactly what I was trying before.  I did just verify that I'm able to upload an image through the current Wordpress app on iOS, and I believe that does resolve my problem from before.  Thanks!
