### ISSUE TITLE
Undefined variable: params

### ISSUE THREAD

**Issue by jackjamieson2** [indieweb/wordpress-indieauth#107]
Since upgrading to 3.1.4 I get the following error when I log in to a microsub client.

PHP Notice: Undefined variable: params in [...]/public_html/microsub-dev/wp-content/plugins/indieauth/includes/class-indieauth-authorize.php on line 118

This error occurs both with either Yarns Microsub Server and the Aperture WordPress plugin.  Additionally, microsub clients are no longer able to retrieve a list of channels, posts, etc.

This is fixed when I downgrade to 3.1.3

**Comment by dshanske** [comment]
Wait... there is no line 118 in the GitHub version...can you test against it?

**Comment by dshanske** [comment]
I may have already fixed this

**Comment by dshanske** [comment]
I am working on a new PR for something else and may ask for a release after for both

**Comment by jackjamieson2** [comment]
You're right, the github master version corrects this issue.  Thank you!
