### ISSUE TITLE
Document the Authorization header fix in the README

### ISSUE THREAD

**Issue by Zegnat** [indieweb/wordpress-indieauth#111]
The current README includes [an entire section on debugging the Unauthorized response](https://github.com/indieweb/wordpress-indieauth/blob/73785711851724342af313a86bffe417646f62b5/readme.md#i-keep-getting-the-response-that-my-request-is-unauthorized). But it doesn’t tell people anything about how to fix it.

Would it make sense to copy [the Micropub plugin’s FAQ item](https://github.com/indieweb/wordpress-micropub/blob/849fddf7e69ff83c591f312c2d1e2076ec4845fe/readme.md#frequently-asked-questions)?

**Comment by dshanske** [comment]
This is now done.
