### ISSUE TITLE
Getting 403 errors On Some Applications

### ISSUE THREAD

**Issue by Changelingmx** [indieweb/wordpress-indieauth#128]
When trying to sign into several services, I get a 403 authorization error. These include but are not limited to Own Your Swarm, Indie Book Club, Monical, Own Your Checkin, and the indigenous app for iOS. When I run the test scrip on these, I get a message saying that the authorization method is depricated.

**Comment by dshanske** [comment]
@Zegnat The authdiag script is yours. Looping you in.

Deprecated: filter_input(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated

**Comment by Zegnat** [comment]
Those two specific flags have been [deprecated as of PHP 7.3](https://secure.php.net/manual/en/migration73.deprecated.php#migration73.deprecated.filter). I’ll see if I can sneak a PR in!

**Comment by dshanske** [comment]
@Changelingmx I've merged in @Zegnat 's fix of the testing to be 7.3 compatible. However, not pushed to wordpress.org yet. That may not solve the problem though.
