### ISSUE TITLE
Add Auth Check to Site Health check

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieauth#139]
https://make.wordpress.org/core/2019/04/25/site-health-check-in-5-2/

5.2 supoorts a site health check section. Checking for the header should be in here too.

**Comment by pfefferle** [comment]
This is a nice idea!

**Comment by dshanske** [comment]
My goal in adding this and other checks is to reduce the amount of issues clients such as the ones @aaronpk supports from getting issues filed over a server problem

**Comment by pfefferle** [comment]
Sure! I have the same issue with the ActivityPub plugin and many others...
