### ISSUE TITLE
Reject requests with invalid scopes

### ISSUE THREAD

**Issue by aaronpk** [indieweb/wordpress-indieauth#157]
Currently the IndieAuth plugin will happily allow an authorization request that contains a scope value with invalid characters, and will also then issue a token with that invalid scope, causing problems later.

OAuth scopes can contain a very limited [set of characters](https://tools.ietf.org/html/rfc6749#section-3.3). [Selfauth](https://github.com/Inklings-io/selfauth/blob/master/index.php#L216) has a regex to match that list of characters.

In particular, it's possible to request a scope value of `create\ndelete` with newlines instead of spaces, which then renders in the authorization screen as a single checkbox showing "create delete" (HTML converts the newline to a space), so to the user it looks like this would work, and then fails on a Micropub request because the scope check splits on spaces instead of newlines.

The plugin should reject the request and not even allow the user to click "authorize" if the scope contains invalid characters.

**Comment by sknebel** [comment]
and for debugging it'd be lovely if it gave some error that contains the sent string clearly encoded so people notice what's going on
