### ISSUE TITLE
Bring Back Remote IndieAuth

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieauth#164]
Originally, I took the advice of removing the ability to set a remote IndieAuth endpoint in favor of local due confusion about how things worked. I am reconsidering that decision and bringing back that functionality.

That would allow the functionality to be stripped out of Micropub and Microsub and be maintained in a single place.

I have a lot of ideas about improving IndieAuth, but maintaining two versions of it, three if you count the fact that Microsub uses a copy of the Micropub file, seems like extra work.

So, in the settings, unlike last time, the goal would be to be very clear the difference between self hosting (default) and using an external endpoint.

Thoughts? @snarfed @pfefferle @jackjamieson2

**Comment by dshanske** [comment]
Looking at this issue and how the settings page might be configured.

**Comment by dshanske** [comment]
#167 restores this capability.

**Comment by snarfed** [comment]
No opinion here! I stopped delegating on my site a while ago.
