### ISSUE TITLE
Use Case: Delegation

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieauth#166]
@pfefferle I think you discussed using the plugin this way.

The idea is that you set one WordPress site to use the IndieAuth endpoint of another WordPress site. Which means it needs to do relmeauth or something similar.

**Comment by dshanske** [comment]
One of the ideas I thought of is using the rest API on WordPress sites to compare users.

**Comment by pfefferle** [comment]
I need only IndieAuth and WebSignIn... no relmeauth... @aaronpk phrased my usecases here https://indieweb.org/Wordpress_IndieAuth_Plugin#Use_Cases

Simply: Use pfefferle.org to login to notiz.blog.

This works btw. with the current version of the plugin.

**Comment by dshanske** [comment]
Someone wanted to do this... maybe it was @tonz . Either way, I want to see if it can work for delegation as part of bringing back remote endpoint support.

**Comment by dshanske** [comment]
I am also curious to implement relmeauth + WordPress rest API user endpoint..

**Comment by dshanske** [comment]
At this time, the better road for delegation seems to be just simple web-signin....both sites can still have their own authorization and token endpoints.
