### ISSUE TITLE
avoid implicit object-instantiation

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-indieauth#168]
A lot of files are self instantiating their classes on the include. I would like to have the instantiating explicit, to be able to test the files and/or to reuse the objects in other contexts.

Examples:
* https://github.com/indieweb/wordpress-indieauth/blob/master/includes/class-indieauth-admin.php#L309
* https://github.com/indieweb/wordpress-indieauth/blob/master/includes/class-indieauth-authorization-endpoint.php#L276
* https://github.com/indieweb/wordpress-indieauth/blob/master/includes/class-indieauth-debug.php#L119
* ...

**Comment by dshanske** [comment]
I switched away from that with the new authorize classes. I can prepare a PR for that after the current one is merged.
