### ISSUE TITLE
Token expiration filter?

### ISSUE THREAD

**Issue by janboddez** [indieweb/wordpress-indieauth#171]
May be a silly thing, but say I would like tokens to automatically expire after, e.g., 15 days. Or even have token lifetime depend on `client_id`.

I was thinking a simple filter hook would make that possible, no?

**Comment by dshanske** [comment]
@janboddez Also a planned future feature. No one implementing IndieAuth has actually done expiring tokens, so I'm waiting for more client support. As of now, if I put in expiring tokens, which, if you look at the code, I actually have the ability to do pretty quickly, the clients would start noting invalid.

I could put it in as an option for manually issued tokens, for now.

**Comment by janboddez** [comment]
Reason I asked is I noticed that once I've logged out (of Aperture or Monocle, in this case) and log back in, a new token gets issued (I'm guessing that's how these things work), and the list of tokens tends to get _quite_ long.

Might try and cook up a way to automatically purge tokens (based off the existing `destroy_older_than()` function, perhaps). Except maybe for a native app like Indigenous, as, like you said, that wouldn't be very practical.

Anyway, that's why I thought a filter hook might work. You could then apply an expiration time _only_ if a value is passed through (by a 3rd-party callback), and leave things exactly as is for everyone else.

**Comment by dshanske** [comment]
There is an option to expire tokens not used in X number of days in the Bulk Actions pulldown.

**Comment by dshanske** [comment]
Resolved in 4.0.0
