### ISSUE TITLE
Authorization has failed!

### ISSUE THREAD

**Issue by Suitbert** [indieweb/wordpress-indieauth#188]
Newbie-Question:
I did install the IndieAuth-plugin and do get the following site-health-message:

_Authorization has Failed
The authorization header was not returned on this test, which means that your server may be stripping the Authorization header. This is needed for IndieAuth to work correctly.

If you are on Apache, try adding this line to your .htaccess file:

SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

If that doesnt work, try this:

RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

If that does not work either, you may need to ask your hosting provider to reconfigure to allow the Authorization header to be passed. If they refuse, you can pass it through Apache with an alternate name. The plugin searches for the header in REDIRECT_HTTP_AUTHORIZATION, as some FastCGI implementations store the header in this location._

I did test the suggested .htaccess-lines. But there was no change in the result. My hoster is all-inkl.com. Sorry, I am not a software-developer. But maybe you will be able to give a hint to this. Thanks!
regards,
Suitbert

**Comment by dshanske** [comment]
@Suitbert Can you check with the latest release and advise?

**Comment by dshanske** [comment]
Closed due lack of response. Reopen if still an issue.
