### ISSUE TITLE
Verifying authorization code fails

### ISSUE THREAD

**Issue by janboddez** [indieweb/wordpress-indieauth#189]
May be overlooking something, but when fiddling with Aperture, which got updated just yesterday to the latest and greatest IndieAuth Client composer package, I kept getting a 'The request is missing one or more required parameters' when trying to validate the authorization code. Apparently, because it would not send a `me` param (with that, second, request).

Replaced line 140 in `class-indieauth-token-endpoint.php` with 
```
		$diff = array_diff( array( 'code', 'client_id', 'redirect_uri'/*, 'me'*/ ), array_keys( $params ) );
```
and all was well again. Doesn't look like _that_ `me` is used anywhere anymore anyway, but again, I could be wrong. Could it be *not actually required*?

See also https://github.com/indieweb/indieauth-client-php/blob/d5b3320cf28f8c6e0f4eb45955288f518d7489f1/src/IndieAuth/Client.php#L373

**Comment by aaronpk** [comment]
yep, the latest change to the indieauth spec drops the `me` parameter from the token request since it's not actually needed.

**Comment by dshanske** [comment]
Working on this for the next version.

**Comment by dshanske** [comment]
@janboddez Can you recheck this with the latest version?

**Comment by janboddez** [comment]
Auto-updated to v3.6.0 the other day, overwriting my previous workaround. Works perfect!
