### ISSUE TITLE
if the site is set to single-user mode, return that user

### ISSUE THREAD

**Issue by aaronpk** [indieweb/wordpress-indieauth#22]
when the indieweb plugin sets the site to single-user mode, there is no reason to search the database for matching users and the one user can be returned instead

**Comment by dshanske** [comment]
Resolved in 5cbc4c43ac34ca10fc9b42b244c17e52b386a409 and fixed in 5e1403a68fefa1c17e3b021867fd12bddbba9e0e, at least for those with the Indieweb plugin installed.
