### ISSUE TITLE
Undefined variable: user_id

### ISSUE THREAD

**Issue by janboddez** [indieweb/wordpress-indieauth#229]
Just a notice: "Undefined variable: user_id in ... /wp-content/plugins/indieauth/indieauth.php"

**Comment by dshanske** [comment]
On it...

**Comment by dshanske** [comment]
Did you have the line number in the file?

**Comment by janboddez** [comment]
Think it was 85, but that it could also be 81 and (?) 83. Seems to call `$user_id` without defining it first.

**Comment by dshanske** [comment]
I have places where I use $user representing the user object and others where I use $user_id representing the id... probably mixed it up
