### ISSUE TITLE
scope parameters get mungled on redirect

### ISSUE THREAD

**Issue by aaronpk** [indieweb/wordpress-indieauth#23]
Something is going wrong with the query string parameters between all the redirect steps.

after i click log in on my client:

`https://tiny.xyz.dev/wp-login.php?redirect_to=https%3A%2F%2Ftiny.xyz.dev%2Fwp-login.php%3Fredirect_to%3Dhttps%253A%252F%252Fmicropub.rocks.dev%252Fendpoints%252Fcallback%26reauth%3D1%26action%3Dindieauth%26client_id%3Dhttps%3A%2F%2Fmicropub.rocks.dev%2F%26state%3D7042033%26scope%3Dcreate+update+delete+undelete%26me%3Dhttps%3A%2F%2Ftiny.xyz.dev`

note that it has the correct `+` between the scope values here.

after i type my password, I get taken to this URL:

`https://tiny.xyz.dev/wp-login.php?redirect_to=https%3A%2F%2Fmicropub.rocks.dev%2Fendpoints%2Fcallback&reauth=1&action=indieauth&client_id=https://micropub.rocks.dev/&state=7042033&scope=createupdatedeleteundelete&me=https://tiny.xyz.dev`

all the spaces are gone from the scope parameter.

(This is on the new `token` branch obviously)

**Comment by dshanske** [comment]
Resolved via 5e1403a68fefa1c17e3b021867fd12bddbba9e0e
