### ISSUE TITLE
indieauth_cleanup expects class Token_User

### ISSUE THREAD

**Issue by janboddez** [indieweb/wordpress-indieauth#235]
```
[21-Aug-2022 08:30:02 UTC] PHP Fatal error:  Uncaught Error: Class "Token_User" not found in <...>/public_html/wp-content/plugins/indieauth/indieauth.php:81
Stack trace:
#0 <...>/public_html/wp-includes/class-wp-hook.php(307): IndieAuth_Plugin::expires()
#1 <...>/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#2 <...>/public_html/wp-includes/plugin.php(524): WP_Hook->do_action()
#3 <...>/public_html/wp-cron.php(138): do_action_ref_array()
#4 {main}
  thrown in <...>/public_html/wp-content/plugins/indieauth/indieauth.php on line 81
```

I recently switched to a remote endpoint, which is why I think `Token_User` is no longer autoloaded when this cron event is run. Maybe add an extra check in there? Or load it regardless, so that old tokens can still be cleaned up?

**Comment by dshanske** [comment]
I haven't tested the remote endpoint code in a while. It's disabled by default. Which remote endpoint are you using?

**Comment by janboddez** [comment]
It's not the remote endpoint per se, just that (I think, from quickly looking through the code) the `Token_User` class does not get included when a remote endpoint is in use. Which I think is why the cleanup "cron job" fails.

If so, you could maybe return early for those on a remote endpoint, or unschedule the cron event, or include the class regardless, so that leftover tokens may be cleaned up automatically (since the token overview in the admin interface is disabled/hidden too). Or something else entirely.
