### ISSUE TITLE
don't generate the authorization code until after the user clicks approve

### ISSUE THREAD

**Issue by aaronpk** [indieweb/wordpress-indieauth#24]
I noticed that the `href` on the authorization form's Approve button is set to the IndieAuth redirect URL and already contains the generated authorization code. Apparently this is something I forgot to mention in my book. It isn't a good idea to generate the authorization code until after the user accepts the request. Probably the easiest way to imagine this problem is if your browser or some extension preloads URLs on the page. Then the code would be sent to the site without the user's interaction.

What I've done with most of my other authorization server implementations is have the "authorize" button submit back to the server, where the code is then generated and the redirect is sent in response to the POST request.

**Comment by dshanske** [comment]
Resolved via 90d3a6afe03a94a9bac1f9c50ac4ad9c7992febe
