### ISSUE TITLE
don't set scopes if response_type=id

### ISSUE THREAD

**Issue by aaronpk** [indieweb/wordpress-indieauth#25]
When response_type=id, there cannot be any scopes generated, since no access token will be issued for that authorization code. Currently the code defaults to `create update` if the client doesn't request a scope. It should not set that if `response_type=id`

https://github.com/indieweb/wordpress-indieauth/pull/20/files#diff-8270c9c52f0edc9e17fb3020914a5752R81

**Comment by dshanske** [comment]
Resolved via d7dbbd4a4c6f8fc6bbe2c31d272f0d6bba7f9a12 athough noted the commit message incorrectly.
