### ISSUE TITLE
Revisit the Removal of the Remote IndieAuth Code

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieauth#253]
In previous iterations, I removed the remote indieauth code, which allowed delegation to an external IndieAuth endpoint. The same code was removed from the Micropub and Microsub plugins. So, I agreed to put it in here disabled,  #164. 

At the time, it was partly because there were people who were using it. However, the landscape has changed. Indieauth.com is on life support, effectively. 

It would certainly simplify things if I removed this code and set up a separate GitHub repository for it if anyone wants to use it or maintain it, but otherwise not keep it in this plugin. But, I wanted to get some input about what the reasons might be to keep it.

I was trying to think about the arguments myself for keeping it, but I can't think of any. If someone has multiple WordPress sites, running the IndieAuth code, the plugin has the web sign-in component so they could log into one site with the credentials of another and I'd like to refresh that a bit as well.

cc: The individuals in the discussion in #164: @snarfed @pfefferle @jackjamieson2 as well as @janboddez who I believe said in an issue that they were using the remote endpoint code at one point

**Comment by janboddez** [comment]
I _did_ use a standalone IndieAuth endpoint at one point in time (when I was still building my own CMS/suite of IndieWeb packages 😂 but hadn't yet moved over fully); I'm now back on WordPress proper (with the IndieAuth plugin doing everything IndieAuth).

It _would_ be cool if one could use, e.g., only the Micropub plugin with a remote endpoint and not need the IndieAuth plugin. A separate or add-on plugin for "remote IndieAuth" would work, too.

But I currently don't need either, so feel free to do whatever works for you!

**Comment by dshanske** [comment]
After consideration, I think I will go the option of extracting the remote code and putting it into it's own GitHub repository.

Considering the local option offers everything, I think people who want to delegate are a minority. For people who want to have multiple sites, web sign in enhancements can address that.

**Comment by dshanske** [comment]
Addressed in #255
