### ISSUE TITLE
Unable to use WP IndieAuth to log into localhost

### ISSUE THREAD

**Issue by lostfocus** [indieweb/wordpress-indieauth#256]
It must have changed with the 4.3.0 version - I used to be able to use my WordPress blog to IndieAuth-login into a localhost dev environment. I tried that just now and I'm running into a infinite loop. The warning is:

```
PHP Warning:  Attempt to read property "textContent" on null in /var/www/blog/wp-content/plugins/indieauth/includes/class-indieauth-client-discovery.php on line 173
```

**Comment by dshanske** [comment]
Interesting.. that's client discovery... shouldn't create a problem....

Working on 4.4 now, will see what I can do here.

**Comment by dshanske** [comment]
Are you using the web sign in button the plugin adds on the local site?

**Comment by lostfocus** [comment]
No, my local site is not running WordPress. I'm putting my URL into the login field on my site on localhost and hope to be able to log in. 

I've tried multiple applications on localhost and they all run into the same problem.

The same applications have no problems logging in when they're on some server somewhere with a "proper" URL.

**Comment by dshanske** [comment]
Well, IndieAuth excludes allowing localhost as a login... could you use a fake host and put it into your hosts file?

**Comment by dshanske** [comment]
Wait...the IndieAuth endpoint is public but the server is local...can you elaborate...same security issue, but I think I might be able to think of something.

**Comment by lostfocus** [comment]
I'm not using localhost as a login. I'm trying to use my blog (WP with this plugin) to log into localhost, which used to work the last time I tried.

**Comment by dshanske** [comment]
Yes, so localhost is following the latest IndieAuth standard?

I want to make sure as I try to reproduce

**Comment by lostfocus** [comment]
It might actually be quite simple. I have my webserver set up in a way that it just returns an empty file (no html) with a 403 header when not using the proper URL. So when WordPress tries to access http://localhost it gets an empty file back. 

So of course `$xpath->query( '//title' )->item( 0 )->textContent` will break because `$xpath->query( '//title' )` has no items and therefore no item 0.

**Comment by dshanske** [comment]
And again, to authenticate to your remote site?

**Comment by dshanske** [comment]
And again, the authenticate to your remote site? I know I'm overthinking it... but I'm making some tweaks for 4.4 and it might affect this beyond the application matter.

**Comment by dshanske** [comment]
> It might actually be quite simple. I have my webserver set up in a way that it just returns an empty file (no html) with a 403 header when not using the proper URL. So when WordPress tries to access http://localhost it gets an empty file back. 
> 
> So of course `$xpath->query( '//title' )->item( 0 )->textContent` will break because `$xpath->query( '//title' )` has no items and therefore no item 0.

I'll have it check for a 403 return though regardless.

**Comment by lostfocus** [comment]
The flow is pretty simple:

```mermaid
flowchart TD
A[http://localhost/login] --> B(Enter `https://lostfocus.de/`)
    B --> C[Error]
```

That used to work. 

<del>I'm not sure my theory with the title is true, though. I've given the 403 page an html title and the problem is still the same.</del>

I've given the 403 page an html title and it works now.

**Comment by dshanske** [comment]
I fixed the issue of it trying to do discovery on anything that isn't a 200 series http code.

But I noticed in https://indieauth.spec.indieweb.org/#client-information-discovery

`If the client_id contains the permitted IPv4 and IPv6 addresses 127.0.0.1 or [::1], or if the domain name resolves to these addresses, the authorization endpoint MUST NOT fetch the client_id.`

I also don't validate the client_id in terms of https://indieauth.spec.indieweb.org/#client-identifier

I do validate some of the token endpoint discovery using https://developer.wordpress.org/reference/functions/wp_http_validate_url/ which actually does unless set, exclude local IPs but not localhost specifically. 

Think I may need to dig a bit on this.

**Comment by gRegorLove** [comment]
If it helps, this is [my implementation](https://github.com/gRegorLove/ProcessWire-IndieAuth/blob/main/src/IndieAuth/Server.php#L19) of the client_id validation.

**Comment by dshanske** [comment]
@lostfocus Want to check this again under 4.4?

**Comment by lostfocus** [comment]
It just goes into a loop now:
```
Failed to Retrieve IndieAuth Client Details {"errors":{"http_request_failed":["A valid URL was not provided."]},
```

**Comment by dshanske** [comment]
Okay, I guess it is time for 4.4.1

**Comment by dshanske** [comment]
> It just goes into a loop now:
> ```
> Failed to Retrieve IndieAuth Client Details {"errors":{"http_request_failed":["A valid URL was not provided."]},
> ```

I'm working on some adjustment of the client discovery code and the client code. I tested validation... I'll try to figure out where the new tests are failing your use case.

**Comment by dshanske** [comment]
@lostfocus Did the last update fix this?

**Comment by lostfocus** [comment]
I didn't really get to test it much since I was busy all December. This part seems to work now.

**Comment by janboddez** [comment]
> `PHP Warning: Attempt to read property "textContent" on null in /var/www/blog/wp-content/plugins/indieauth/includes/class-indieauth-client-discovery.php on line 173`

I ran into this exact issue (except it's line 153) just now... Quill works okay and I guess IndiePass too, but when I try to sign in to indieweb.org (via indielogin.com, I think) it generates this error a bunch of times and eventually times out.

I have to admit, I haven't logged in to indieweb.org since forever.

Also, it keeps showing the login form, while in another browser tab I'm still logged in OK. When I then tried Quill, just to see what'd happen, WP never showed the login form and went straight to the auth form instead.

**Comment by janboddez** [comment]
Tried again trying to work around this, but I now just get a "too many redirects" error trying to log in to indieweb.org.

Regardless, I think there may be room for improvement here:
```
private function get_html( $input ) {
  if ( ! $input ) { // Input seems to be an instance of \DOMDocument, so we don't get to return early.
    return;
  }

  $xpath               = new DOMXPath( $input );
  $this->html['title'] = $xpath->query( '//title' )->item( 0 )->textContent; // We somehow can't get a title at all.
}
```
Also, even if `$input` were `null` or `false` and the function would return early, you'd just get a different error later on: `Undefined array key "title" in indieauth/includes/class-indieauth-client-discovery.php on line 111`. The rest of the code really expect there to be a title.

Now, if only I knew why my server isn't getting any HTML at all ...

**Comment by janboddez** [comment]
> Now, if only I knew why my server isn't getting any HTML at all ...

Ha, I now know. It's giving me ... JSON.

Response body is the following ... `{"client_id":"https:\/\/indielogin.com\/id","client_name":"IndieLogin.com","client_uri":"https:\/\/indielogin.com\/","logo_uri":"https:\/\/indielogin.com\/icons\/apple-touch-icon.png","redirect_uris":["https:\/\/indielogin.com\/redirect\/indieauth"]}`

Going to be difficult finding a `title` element, I guess. Response `content-type` is `application/json` too.

Thing is, is this the remote server or the plugin? And shouldn't error handling be improved, then?
