### ISSUE TITLE
Permission Error with Jetpack

### ISSUE THREAD

**Issue by ChaosExAnima** [indieweb/wordpress-indieauth#265]
It appears that there's a conflict with this plugin and the popular [Jetpack](https://github.com/automattic/jetpack) plugin. When this plugin is activated, attempting to access the Jetpack dashboard results in a "You are not allowed to access this page" error, even as an admin.

Steps to reproduce (I used [Studio](https://developer.wordpress.com/studio/) for a clean site):

1. Install IndieAuth and the Jetpack plugin.
2. Activate Jetpack.
3. Visit the Jetpack dashboard page, verifying no permission issues.
4. Activate the IndieAuth plugin.
5. Retry 3.

Expected: Jetpack dashboard is accessible.
Actual: Jetpack dashboard shows WordPress error "Sorry, you are not allowed to access this page".

I took a quick look at the code, but wasn't able to spot anything that was obviously the culprit. There's nothing in the PHP logs either.

**Comment by dshanske** [comment]
@ChaosExAnima Will look into this. Don't use Jetpack myself, but assume it is our login code interfering with theirs. It shouldn't, but...

**Comment by dshanske** [comment]
@akirk Worried this may affect the same code you've been submitting PRs for.

**Comment by Kadams64** [comment]
I am seeing the same problem re: Jetpack and IndieAuth.  JetPack features fail with "You are not allowed to access this page" If IndieAuth is active
- Wordpress 6.6.1
- IndieAuth 4.5.0

I skimmed the [JetPack 'Known issues' page](https://jetpack.com/support/getting-started-with-jetpack/known-issues/) and saw this reference about [conflicts with plugins that change or restrict access to the WordPress REST API](https://jetpack.com/support/getting-started-with-jetpack/known-issues/#plugins-that-restrict-access-to-the-rest-api) that might (?) be relevant.

**Comment by dshanske** [comment]
This doesn't do that...I am going to have to dig into what might be causing it. Unless Jetpack doesn't like sharing the connection...

**Comment by dshanske** [comment]
@Kadams64 Do you want to try the update and see if you are satisfied?

**Comment by Kadams64** [comment]
> @Kadams64 Do you want to try the update and see if you are satisfied?

It appears to solve the Jetpack conflict!  

I downloaded the current trunk and activated it, then tested each of the Jetpack left nav links: the permissions issue with "You are not allowed to access this page" no longer occurs and the expected Jetpack pages render.  
- I don't have a good test at hand for the Indieauth endpoint (I'm a complete IndieAuth newcomer), so I just did a quick test of the Wordpress login "Web sign-in" interface

I am assuming that this hasn't been pushed as an update to the Wordpress plugins repository?

**Comment by dshanske** [comment]
> > @Kadams64 Do you want to try the update and see if you are satisfied?
> 
> It appears to solve the Jetpack conflict!  
> 
> I downloaded the current trunk and activated it, then tested each of the Jetpack left nav links: the permissions issue with "You are not allowed to access this page" no longer occurs and the expected Jetpack pages render.  
> - I don't have a good test at hand for the Indieauth endpoint (I'm a complete IndieAuth newcomer), so I just did a quick test of the Wordpress login "Web sign-in" interface
> 
> I am assuming that this hasn't been pushed as an update to the Wordpress plugins repository?

Go to indielogin.com and you can test there.

And it will be... thought it was worth having you check first after we accepted the PR for this fix.

**Comment by Kadams64** [comment]
Indielogin.com's test work's perfectly on my site with the IndieAuth plugin enabled, so I'd say the fix is working correctly all around.

Thanks for inviting me to help test it, and thanks of course for the fix!

**Comment by pfefferle** [comment]
I will close the issue then, please re-open if still an issue!
