### ISSUE TITLE
Update Discovery with Support for New Proposed Discovery Method

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieauth#267]
https://github.com/indieweb/indieauth/issues/133

https://drafts.aaronpk.com/draft-parecki-oauth-client-id-metadata-document/draft-parecki-oauth-client-id-metadata-document.html

**Comment by janboddez** [comment]
Ha, this must be why I can't log in to the IndieWeb wiki. Right?

Looks like Indielogin.com has already switched to JSON client metadata, and the plugin isn't yet compatible. https://github.com/aaronpk/indielogin.com/blob/35c8aa0ae627517d9c9a9578b901740736ded428/app/Controller.php#L18

Edit: just seeing the PR now. I'll try it when I can. Aaron's also right, the error handling can be improved. E.g., there _seem_ to be some checks in the code (`if ( ! $input ) ...` and the like), but they may be ineffective. Might be able to help out there, I'll see what I can do.

**Comment by dshanske** [comment]
Merged via #268
