### ISSUE TITLE
use alternative text for response_type=id

### ISSUE THREAD

**Issue by aaronpk** [indieweb/wordpress-indieauth#27]
When response_type=id, it means the application is asking to log you in, rather than asking to do anything to your website. It makes sense to change the authorization prompt to reflect this, since continuing the flow won't actually allow the app to "access your site". Maybe something along the lines of this:

![screenshot 2018-04-04 13 03 43](https://user-images.githubusercontent.com/113001/38331638-9de2961e-3808-11e8-8b6f-913cae95f6d9.png)

Note that the wordpress user in this case is not significant, since the app you're signing in to will not know the difference. All they will get is the profile URL of the website.

**Comment by dshanske** [comment]
Going to create a second template file

**Comment by dshanske** [comment]
Resolved via 5cf254d35174b5a72ae3f24625625bd00b9a2688
