### ISSUE TITLE
Check for presence of cookie

### ISSUE THREAD

**Issue by aaronpk** [indieweb/wordpress-indieauth#48]
Currently if you end up here without the cookie being set, you get an error in the logs and things break. Need to check for the cookie being present and show a better error if it is not.

https://github.com/indieweb/wordpress-indieauth/blob/ce32028d5b4e56739cd76731185c133f3fe5cfe0/includes/class-indieauth-authenticate.php#L390

**Comment by pfefferle** [comment]
Yes, I think this was my „Hack“...

**Comment by dshanske** [comment]
Resolved via https://github.com/indieweb/wordpress-indieauth/commit/4463213f71f1f9f4b6b46a95dd39987b544d04ac
