### ISSUE TITLE
Your have entered a valid Domain, but you have no account on this blog.

### ISSUE THREAD

**Issue by svandragt** [indieweb/wordpress-indieauth#5]
As per https://wordpress.org/support/topic/your-have-entered-a-valid-domain-but-you-have-no-account-on-this-blog/#post-8702013

Summary:
With the site URL in my user profile, and the rel="me" invisible link element in my template, I'm still unable to authenticate, with the error above shown in my login screen. I successfully authenticate with GitHub or Twitter and get sent back to my WordPress site but I won't get logged in.

Example URL https://vandragt.com 

PHP7, nginx

**Comment by svandragt** [comment]
Think I have found the bug, somewhere in my database it is still thinking my site is on HTTP, as the indie auth prompt says: 

Authenticate using one of the methods below to sign in as http://vandragt.com/

**Comment by pfefferle** [comment]
But I think the plugin should be able to handle both versions http and https.

**Comment by svandragt** [comment]
So what happens is that if you type in your domain without the protocol IndieAuth sees it as http, whereas if you type https://<domain> into the box it works as expected and logs you in correctly.

**Comment by dshanske** [comment]
I think has been resolved now. Can you check again?

**Comment by svandragt** [comment]
Sure I’m happy to try and set this up again soon.

**Comment by dshanske** [comment]
Closing this due age. Feel free to reopen.
