### ISSUE TITLE
Getting error Missing Parameter: redirect_uri even when a redirect URI is present

### ISSUE THREAD

**Issue by kimberlyhirsh** [indieweb/wordpress-indieauth#53]
Getting this error:
{"error":"parameter_absent","error_description":"Missing Parameter: redirect_uri"}

This error occurs when using Micropub (tried with ownyourgram and Teacup) and when trying to log in to the Indieweb wiki. But there is in fact a redirect URI - for example, when using Teacup, this is in my address bar:

http://kimberlyhirsh.com/wp-json/indieauth/1.0/auth?me=http%3A%2F%2Fkimberlyhirsh.com%2F&redirect_uri=https%3A%2F%2Fteacup.p3k.io%2Fauth%2Fcallback&client_id=https%3A%2F%2Fteacup.p3k.io&state=97bd85bbcb5deb96&scope=create&response_type=code

**Comment by snarfed** [comment]
also filed on snarfed/wordpress-micropub#137. thanks again for the nudges @kimberlyhirsh. which versions of the plugins are you using?

cc @dshanske. you all have been debugging this on IRC too, right? sorry if we're repeating ourselves.

**Comment by dshanske** [comment]
I have, but I am stumped. It isn't a Micropub problem, solely an IndieAuth one.

**Comment by dshanske** [comment]
But clearly, by @kimberlyhirsh  statement, it is happening even with Indieauth.com, which suggests something browser side.

**Comment by philbowell** [comment]
I believe I am also having this issue with [my site](https://philbowell.blog). I receive the same error when I try and log in to anything using my domain and this plugin. I’ve tried Quill, Indieweb.com, and Indigeous on my iPhone and receive this error each time.

**Comment by kimberlyhirsh** [comment]
I'm using IndieAuth 3.1.1 and Micropub 1.4.3.

**Comment by dshanske** [comment]
@philbowell @kimberlyhirsh We found that one individual has a mod_security rule on their server that filtered URLs in query parameters. Any chance you could talk to your hosting providers?

**Comment by stephenpieper** [comment]
The mod_security rule that caused my problem is rule 340162
https://wiki.atomicorp.com/wiki/index.php/WAF_340162

My hosting provider whitelisted the rule and Indieauth works again.

**Comment by dshanske** [comment]
Closed due this now referenced in readme
