### ISSUE TITLE
Rename this plugin.

### ISSUE THREAD

**Issue by Zegnat** [indieweb/wordpress-indieauth#6]
The name might give a wrong idea about what the plugin does.

This plugin does not allow people to login with their IndieAuth endpoint without going through IndieWeb.com (as @cweiske mentions in #2) nor does it help people get an IndieAuth endpoint on their own site. In fact it doesn’t seem to do anything with [IndieAuth](https://indieweb.org/IndieAuth) (see [how IndieAuth works](https://indieweb.org/IndieAuth#How_it_works)).

This plugin allows someone to use IndieAuth.com (the service) to login. That’s not IndieAuth by itself and @aaronpk will be [renaming the service to indielogin](https://chat.indieweb.org/meta/2017-07-19/1500481059573000) (scope [described here](https://chat.indieweb.org/meta/2017-07-19/1500481422110000)).

I would recommend renaming it to [Web sign-in](http://indieweb.org/Web_sign-in) which is the service agnostic name for “logging in with a URL as identity”.

**Comment by pfefferle** [comment]
Thanks for summing this up!

I share your concerns, but I would prefer changing the plugin to a fully compatible IndieAuth provider... It was always planned, but it is a question of spare time :(

The implementation of the IndieAuth.com sign in was only a quick first shot.

**Comment by Zegnat** [comment]
> <i>[…]</i> I would prefer changing the plugin to a fully compatible IndieAuth provider... It was always planned, but it is a question of spare time :(

That’s a pretty big 180° spin for the plugin though. You’d go from using IndieAuth.com for the blog’s login back to the usual WordPress one. Would this not upset current users of the plugin?

**Comment by cweiske** [comment]
> to a fully compatible IndieAuth provider.

"Provider" or do you want to implement full indieauth protocol support (instead of indieauth.com-only support)?

**Comment by dshanske** [comment]
I'm planning to work on making this full indieauth protocol support as a Stage 1. Two being looking into making one of those options its own provider.

**Comment by dshanske** [comment]
The plugin now supports IndieAuth for Authentication in the login page and IndieAuth Bearer Tokens as an authentication method. It has settings to try alternate servers. So, it should now be protocol compliant. Closing on that basis, although testing is appreciated.
