### ISSUE TITLE
Error: IndieAuth Server did not return the same state parameter

### ISSUE THREAD

**Issue by EdwardHinkle** [indieweb/wordpress-indieauth#70]
The error as described here https://github.com/EdwardHinkle/indigenous-ios/issues/195 is:

I enter my domain name (https://www.serenawho.com) and log into my WordPress site. The next page that loads asks me to authorise the app, but gives me a warning:

>**Warning:** The redirect URL this app is using does not match the domain of the client ID.

I click Authorise anyway and it takes me back to my WordPress login page with the error:
>IndieAuth Server did not return the same state parameter

Am I doing something wrong?

**Comment by EdwardHinkle** [comment]
I have had this same issue running the latest version of the plugin on my own Wordpress test instance.

It seems to be an issue with the cookie that is used to retain the state parameter when you are logged out at the beginning of the IndieAuth flow and are logged in at the end of the flow.

@aaronpk thought maybe the cookie is deleted as part of the log in process

**Comment by EdwardHinkle** [comment]
It looks like this was fixed through changing the redirectUri from indigenous://callback/path to a page on https://indigenous.abode.pub/ios that redirects to indigenous://callback/path. So this issue is resolved for Indigenous, however there seems to be some strange underlying issue with the app schemes. I don't know if that means we want to suggest people NOT use those or if we need to do a lot of debugging on our IndieAuth endpoints for them.

**Comment by aaronpk** [comment]
This is probably actually related to #82 and #76

**Comment by pfefferle** [comment]
duplicate
