### ISSUE TITLE
Login to 🕸💍.ws does not work

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-indieauth#76]
error: The authorization server returned an invalid state parameter

**Comment by dshanske** [comment]
My theory is that it is checking for valid URLs. Maybe we need a different validator.

**Comment by pfefferle** [comment]
I don't think so, because 🕸💍.ws is printing the error, if it is a validation problem, my blog would print the error!?!

**Comment by dshanske** [comment]
I had a similar problem with indiebookclub and it turned out to be a cookie in the browser

**Comment by pfefferle** [comment]
All cookies cleared, with no effect :(

**Comment by aaronpk** [comment]
It appears the plugin is messing up the URL escaping of the state parameter. I made a test indieauth client that sets intentionally tricky characters for the state parameter.

https://indieauth.rocks/client/state/

I'm guessing there's some combination of `wp_unslash` / `rawurlencode` function calls that are messing it up.

**Comment by pfefferle** [comment]
I fear it is a problem of some core functionalities... simply removing wp_unslash and rawurlencode does not help :(

**Comment by pfefferle** [comment]
We should write a unit-test for that...

**Comment by pfefferle** [comment]
WordPress' `add_query_arg` uses `urlencode_deep`, so we have to replace that core function and build the query string "by hand".

**Comment by aaronpk** [comment]
Feel free to pull from https://github.com/aaronpk/p3k-utils/blob/master/src/url.php#L12 and https://github.com/aaronpk/p3k-utils/blob/master/src/url.php#L79

**Comment by pfefferle** [comment]
Oh nice!

@aaronpk nevertheless, wouldn't it be more solid to change the spec to require only URL save chars? there might be other side effects if the state uses chars like `=`, `&` or `#`.
