### ISSUE TITLE
Confirmation screen shows wrong URL

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-indieauth#77]
I use `notiz.blog` as login

<img width="620" alt="bildschirmfoto 2018-07-02 um 15 32 00" src="https://user-images.githubusercontent.com/2373/42167051-1cdb2c34-7e0d-11e8-939b-8fc178c2a349.png">

and the confirmation screens says `pfefferle.org`

<img width="548" alt="bildschirmfoto 2018-07-02 um 15 31 44" src="https://user-images.githubusercontent.com/2373/42167054-1e6d1a76-7e0d-11e8-9a7b-8f4da44bda0c.png">

It seems to use the `user_url` instead of the `me` URL.

**Comment by dshanske** [comment]
Resolved in 3.0.3
