### ISSUE TITLE
Cannot login to IndieWeb Readers

### ISSUE THREAD

**Issue by davidmead** [indieweb/wordpress-indieauth#78]
I couldn't log in to the Indigenous (Android) reader.  I [posted the issue](https://github.com/swentel/indigenous-android/issues/90) and the topic of the IndieAuth plugin came up.  I updated to Version 3.0.2 of IndieAuth and still cannot login in to Indigenous, *but* I now can't log in to Together either.

That returns an error of 'Authentication timed out' on both laptop and tablet.

<img width="380" alt="together-login_error" src="https://user-images.githubusercontent.com/1266930/42281820-b1e35f48-7f72-11e8-92db-298a1d43abef.png">

I can still log into to things like Quill though.

**Comment by dshanske** [comment]
Have we followed up on this recently?

**Comment by davidmead** [comment]
I have been logging fine for a while now.  I think it's been good since a WP plugin was updated (maybe IndieAuth?).
