### ISSUE TITLE
WordPress indieauth plugin: Error when I go to [settings]Indieweb->IndieAuth

### ISSUE THREAD

**Issue by dougbeal** [indieweb/wordpress-indieauth#84]
Fatal error: Uncaught Error: Call to undefined function get_indieauth_authorization_endpoint() in /var/www/html/wp-content/plugins/indieauth/templates/indieauth-settings.php:2 Stack trace: #0 /var/www/html/wp-includes/template.php(688): require_once() #1 /var/www/html/wp-content/plugins/indieauth/includes/class-indieauth-admin.php(75): load_template(‘/var/www/html/w…’) #2 /var/www/html/wp-includes/class-wp-hook.php(286): IndieAuth_Admin-&gt;settings_page(”) #3 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook-&gt;apply_filters(”, Array) #4 /var/www/html/wp-includes/plugin.php(453): WP_Hook-&gt;do_action(Array) #5 /var/www/html/wp-admin/admin.php(224): do_action(‘indieweb_page_i…’) #6 {main} thrown in /var/www/html/wp-content/plugins/indieauth/templates/indieauth-settings.php on line 2

Was the setting supposed to go away?

(Originally published at: https://crw.moe/b/V5)

**Comment by pfefferle** [comment]
is fixed in version 3.0.4
