### ISSUE TITLE
upgrading to 3.1.0 stops my site working altogether

### ISSUE THREAD

**Issue by troutcolor** [indieweb/wordpress-indieauth#86]
Hi,
I upgraded the plugin  via wp-admin/update-core.php 
My site 
http://johnjohnston.info/blog
Disappeared both front and back end. I've removed the plugin via ftp and the site came back.

cheers

john

**Comment by dshanske** [comment]
Is there anything in the logs that might indicate why?

**Comment by dshanske** [comment]
We'll try to figure it out regardless as a priority

**Comment by troutcolor** [comment]
@dshanske 
Thanks.
I turned logging on and see:
Parse error: syntax error, unexpected '[' in /Customer Web Sites/johnjohnston/public_html/blog/wp-content/plugins/indieauth/includes/functions.php on line 314

**Comment by troutcolor** [comment]
Brilliant, installed the new version and my site is fine.
Many thanks.
