### ISSUE TITLE
The display of the scopes is a bit wonky

### ISSUE THREAD

**Issue by chrisaldrich** [indieweb/wordpress-indieauth#88]
![](https://i2.wp.com/boffosocko.com/wp-content/uploads/2018/07/IndieAuth-display-error.png?resize=319%2C496&amp;ssl=1)
There’s a small quirk in the display of the scopes on the “Authorize" page.

(Originally published at: https://boffosocko.com/2018/07/22/the-display-of-the-scopes-is-a-bit-wonky-in-indieauth-plugin/)

**Comment by dshanske** [comment]
Resolved via #89

**Comment by dshanske** [comment]
Sorry about that
